version: "3.8"

services:

  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - ${NATS_CLIENT_PORT}:4222

volumes:
  postgres-data:
