on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    strategy:
      matrix:
        bun-version: [latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        name: Use Bun ${{ matrix.bun-version }}
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Build
        run: |
          bun i
          bun run build
